(setq scheme-program-name "/usr/local/bin/chez")
(unless (file-exists-p scheme-program-name)
  (message "Installing Chez Scheme")
  (shell-comand "brew install chezscheme"))
(setq ispell-program-name "/usr/local/bin/aspell")
(unless (file-exists-p ispell-program-name)
  (message "Installing aspell")
  (shell-comand "brew install aspell"))
(defvar ben/default-font-size 12)
(setq system-uses-terminfo nil)
  
(provide 'siraben-macos)
