# Hardware configuration for Beelink Mini S12 Pro
# This should be replaced/merged with the output of 'nixos-generate-config'
# on the actual hardware

{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  # Boot configuration for Intel N100
  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
    "rtsx_pci_sdmmc"
  ];
  
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  # Example filesystem configuration - REPLACE WITH YOUR ACTUAL SETUP
  # Generated by 'nixos-generate-config --root /mnt'
  fileSystems."/" = {
    device = "/dev/disk/by-label/nixos";
    fsType = "ext4";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-label/BOOT";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  # Swap configuration (optional - uncomment if you have swap)
  # swapDevices = [
  #   { device = "/dev/disk/by-label/swap"; }
  # ];

  # Hardware configuration
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
  hardware.enableRedistributableFirmware = true;
  hardware.enableAllFirmware = true;

  # Network interfaces (adjust based on your hardware)
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0.useDHCP = lib.mkDefault true;  # Ethernet
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;  # WiFi

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}