name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: cachix/install-nix-action@v17
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v10
        with:
          name: siraben
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: nix-shell -p home-manager --run "home-manager build -f home-manager/.config/nixpkgs/home.nix"
