name: Build

on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: [macos-12, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4.1.1
      - uses: cachix/install-nix-action@v26
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: cachix/cachix-action@v14
        with:
          name: siraben
          authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
      - name: Build
        run: nix-shell -p home-manager --run "home-manager build -f home-manager/.config/nixpkgs/minimal.nix"
