name: Build

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-24.04, macos-15]
    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4.2.2

      - uses: cachix/install-nix-action@v31.3.0
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - uses: cachix/cachix-action@v16
        with:
          name: siraben
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}

      - name: Build home-manager config
        run: nix-shell -p home-manager --run "home-manager build -f home-manager/.config/nixpkgs/home.nix"
